using Ecommerce.Domain.Enums;

namespace Ecommerce.Application.Sales.GetPaginatedSales;

public class GetPaginatedSaleResult
{
    public Guid Id { get; set; }

    /// <summary>
    /// Gets the sale number.
    /// Sequence number generated by the system to identify the sale.
    /// </summary>
    public int Number { get; set; }

    /// <summary>
    /// Gets the date and time when the sale was made.
    /// use the time zone utc to save the date
    /// </summary>
    public DateTime Date { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Gets the total value of the sale.
    /// must be calculated based on the sum of the products in the sale.
    /// </summary>
    public decimal TotalValue { get; set; }

    /// <summary>
    /// gets the sale.status
    /// </summary>
    public SaleStatus Status { get; set; } = SaleStatus.Active;

    /// <summary>
    /// Gets the number of products in the sale.
    /// </summary>
    public int ProductCount { get; set; }
}